### PR TITLE
Add "SVG to 2D mesh importing" to roadmap

### PR DESCRIPTION
**Pull request by sbeca**
I understand that the Godot Editor has support for SVG files for Editor icons but it would be great to also have support for SVGs in-game.

My day job company uses a different engine and our entire art pipeline for our current games are based around SVGs. Using SVGs reduces our build size and gives us resolution independent art which is great. If I'm ever going to be able to convince my company to switch to Godot, I'll need a path to be able use our existing SVG art in Godot.

EDIT: I have updated/changed this PR. Please see my latest comment for details.

### CODE REVIEW

**Comment by djrm** [comment]
Godot 3.0 already supports SVG, although a little bit limited it could be improved in the future.

**Comment by sbeca** [comment]
That's good to hear @djrm. I have only seen it used in the Editor, are there any examples/docs of using them in builds? Sorry about my inexperience, I've only recently started looking into/experimenting with Godot

**Comment by djrm** [comment]
@sbeca currently godot 3.0 is in alpha stage, you can compile it (its quite easy http://docs.godotengine.org/en/stable/development/compiling/index.html), after that using SVG in godot is really straightforward, just drop your SVGs into your project folder, and they will be imported automatically (transformed to textures), converting the SVG to geometry is not currenlty supported, but you can change the generated texture scale, in the import panel. 
screenshot from 2017-09-25 20-19-26

that will redraw the texture to the specified resolution. another thing is that the current importer only supports SVGs with pixel units.

**Comment by sbeca** [comment]
Thank you so much @djrm for explaining all this. Just to make sure that I correctly understand the current state of affairs, SVGs will be transformed into textures within the Editor and those textures are included in an exported build, not the SVGs?

If that is the current state, then there is no way to change the resolution of the transformed textures within an exported build and build size is affected by transformed texture size, not SVG size, correct?

Our current pipeline transforms SVGs into meshes with vertex colouring (no textures at all) which allows a good mix between build size and resolution independence. I would love to see a system that can achieve similar goals in Godot.

**Comment by djrm** [comment]
@sbeca yeah thats exactly how it currenlty works, this solution was more for the icons rendering, but 2d meshes are planed for 3.1, and SVG to 2D meshes is in my TODO list, but we are currently in 3.0 alpha, so 3.1 will take some time.

**Comment by sbeca** [comment]
I understand that these things take time @djrm. To that effect, I've updated this PR from adding "SVG support" to adding "SVG to 2D mesh importing" to better reflect what has yet to happen.

**Comment by toger5** [comment]
This is now added to the roadmap:
https://github.com/godotengine/godot-roadmap/blob/master/ROADMAP.md#2d-rendering-features

SO it could get closed

**Pull request closed without merging**
